### ISSUE TITLE
Shouldn't EmployeeID references to ReportsTo?

### ISSUE THREAD

**Issue by metinsenturk** [jpwhite3/northwind-SQLite3#4]
EmployeeID referring to EmployeeID seems weird. I tried it works, but shouldn't the foreign key be set to `ReportsTo` column?

https://github.com/jpwhite3/northwind-SQLite3/blob/591cd3253c327b1eed7155c1fec57464565c0932/Northwind.Sqlite3.create.sql#L279

I checked the Microsoft SQL samples for this table and they also have it referred to `ReportsTo`. Have a look at [microsoft/sql-server-samples](https://github.com/microsoft/sql-server-samples/blob/master/samples/databases/northwind-pubs/instnwnd.sql). 

Correct foreignkeyconstraint should be:

``` sql
FOREIGN KEY ([ReportsTo]) REFERENCES [Employees] ([EmployeeID]) 
		ON DELETE NO ACTION ON UPDATE NO ACTION
```

**Comment by jpwhite3** [comment]
Thanks for reporting the issue. Script has been updated.
