### ISSUE TITLE
Use tags please

### ISSUE THREAD

**Issue by JoshuaBehrens** [jpwhite3/northwind-SQLite3#9]
When you expect others relying on this data you should use tags. This makes it easy for the users to still use the old table structure before your recent restructures.

**Comment by jpwhite3** [comment]
Great suggestion @JoshuaBehrens - I've added a tag for both the previous version and the latest. Those looking for the older code can now grab that from here: https://github.com/jpwhite3/northwind-SQLite3/releases/tag/v0.1.0

It is probably a good idea to implement testing, CI, and a controlled release process at this point. Contributions are welcome!

**Comment by JoshuaBehrens** [comment]
Thank you very much for the old tag :) I am not very good at GitHub Actions, but I can see myself on Makefiles running tests with bats or similar. What kind of tests do you think about?

**Comment by jpwhite3** [comment]
Great question 🤔. I'm thinking some simple characterization tests to start with. Something to assert that table names, column names, data types, relationships, etc. are all correct. That would be a good start. I may take a stab at roughing something out and running it via GH Actions in the coming weeks.

**Comment by JoshuaBehrens** [comment]
I am thrilled. Data that is almost 50 years old getting so much attention :D
